networks:
  yourcallsheet-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      yourcallsheet-net:
        ipv4_address: 172.28.0.3
    environment:
      SERVER_PORT: 8080

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
#     POSTGRES_DB:mydatabase
#     POSTGRES_PASSWORD:secret
#     POSTGRES_USER:myuser
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql
    networks:
      yourcallsheet-net:
        ipv4_address: 172.28.0.2
    ports:
      - '5432:5432'   #Todo change for prod
