server:
  port: ${SERVER_PORT:-8080}

spring:
  application:
    name: yourcallsheet
  datasource:
    username: user
    password: secret
    url: jdbc:postgresql://172.28.0.2:${DB_PORT:-5432}/yourcallsheet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      file: docker-compose.dev.yml
